# Generic makefile - Unix (hp) version
# 
            LDLIBS = -lMrm -lXm  -lXt -lXmu -lX11
         LDOPTIONS = 
            CFLAGS = -g -I./ $(DEFINES)
                RM = rm -f
               UIL = /usr/bin/uil

include CommonMakefile

$(PGM):: $(OBJS) 
	$(RM) $@
	$(CC) -o $@ $(OBJS) $(LDOPTIONS) $(LDLIBS)



